name: SweetPlayerMarket
version: '${version}'
main: top.mrxiaom.sweet.playermarket.SweetPlayerMarket
api-version: 1.13
softdepend:
  - Vault
  - PlayerPoints
  - MPoints
  - PlaceholderAPI
  - LangUtils
  - ItemsAdder
  - MythicLib
  - MMOItems
  - MythicMobs
  - CraftEngine
  - NeigeItems
  - DynamicBind
authors: [ MrXiaoM ]
folia-supported: true
# PluginBase Libraries ${libraries_config}
commands:
  sweetplayermarket:
    description: 'The main command of SweetPlayerMarket'
    aliases: [ spm, pm, playermarket ]
